version: '3'

services:

  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=eleitoral
    volumes:
    - ./mysql-volume:/var/lib/mysql
    ports:
      - 3307:3306

  spring-app:
    build:
      context: "./"
      dockerfile: "Dockerfile"

    ports:
    - 8080:8080
    depends_on:
      - mysql-standalone




